name: giyeong_um_porfolio_page
description: GiYeongUM Portfolio Page with Flutter
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #State manage
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.1.0

  #logic
  copy_with_extension: ^5.0.3
  json_annotation: ^4.7.0
  intl: ^0.18.0

  #view
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  responsive_framework: ^0.2.0
  shimmer: ^3.0.0
  date_picker_timeline: ^1.2.5

  #util
  http: ^1.1.0
  logger: ^1.1.0
  package_info_plus: ^4.1.0
  flutter_secure_storage: ^6.1.0
  shared_preferences: ^2.0.17
  go_router: ^8.1.0

  #firebase

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  source_gen: ^1.3.2
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3
  copy_with_extension_gen: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: LINESeedKR
      fonts:
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Th.otf
          weight: 100
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Rg.otf
          weight: 400
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Bd.otf
          weight: 700