name: portfolio
description: GiYeongUM Portfolio

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State manage
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.1.0

  #logic
  http: ^0.13.5
  flutter_secure_storage: ^6.1.0
  shared_preferences: ^2.0.17
  json_annotation: ^4.7.0
  url_launcher: ^6.1.10
  http_parser: ^4.0.2
  go_router: ^8.1.0
  copy_with_extension: ^5.0.3

  #view
  flutter_icon_snackbar: ^1.1.4
  flutter_icon_dialog: ^1.2.1
  icon_animated: ^1.2.1
  flutter_static_utility: ^1.0.2
  responsive_framework: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  cached_network_image: ^3.2.3
  hashtagable: ^2.1.0
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  animated_digit: ^3.2.1
  flutter_html: ^3.0.0-beta.1
  auto_size_text: ^3.0.0
  blurrycontainer: ^1.0.2
  flutter_colorpicker: ^1.0.3
  visibility_detector: ^0.3.3
  image_picker: ^0.8.7+5
  modal_bottom_sheet: ^3.0.0-pre
  confetti: ^0.7.0
  flutter_typeahead: ^4.3.3
  html_editor_enhanced: ^2.5.1
  lottie: ^2.5.0
  flutter_spinkit: ^5.2.0

  #util
  url_strategy: ^0.2.0
  logger: ^1.1.0
  kakao_flutter_sdk: ^1.3.0
  sign_in_with_apple: ^5.0.0
  intl: ^0.18.0
  device_info_plus: ^9.0.2
  package_info_plus: ^3.1.2
  permission_handler: ^10.2.0
  fl_chart: ^0.61.0
  file_picker: ^5.2.7
  envied: ^0.3.0+3
  encrypt: ^5.0.1
  pasteboard: ^0.2.0
  string_validator: ^1.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  source_gen: ^1.3.2
  build_runner: ^2.4.4
  json_serializable: ^6.5.4
  envied_generator: ^0.3.0+3
  copy_with_extension_gen: ^5.0.3
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: CabinetGrotesk
      fonts:
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Thin.otf
          weight: 100
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Bold.otf
          weight: 700
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Cabinet_Grotesk_OTF/CabinetGrotesk-Black.otf
          weight: 900
    - family: LINESeedKR
      fonts:
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Th.otf
          weight: 100
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Rg.otf
          weight: 400
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Bd.otf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

