name: giyeong_um_porfolio_page
description: GiYeongUM Portfolio Page with Flutter
publish_to: 'none'

version: 1.2.0+10

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State manage
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0

  #logic
  stream_transform: ^2.1.0
  copy_with_extension: ^5.0.3
  json_annotation: ^4.7.0
  go_router: ^8.1.0
  url_launcher: ^6.2.1

  #view
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  responsive_framework: ^1.1.1
  shimmer: ^3.0.0
  date_picker_timeline: ^1.2.5
  lottie: ^2.7.0
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  smooth_scroll_multiplatform: ^1.0.8
  flutter_animate: ^4.3.0
  blur: ^3.1.0
  cached_network_image: ^3.3.0
  dropdown_button2: ^2.3.9

  #util
  http: ^1.1.0
  logger: ^1.1.0
  intl: ^0.18.1
  intl_translation: ^0.18.2
  url_strategy: ^0.2.0

  #firebase
  firebase_core: ^2.20.0
  firebase_performance: ^0.9.3+6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  source_gen: ^1.3.2
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3
  copy_with_extension_gen: ^5.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/json/
    - assets/images/

  fonts:
    - family: LINESeedKR
      fonts:
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Th.otf
          weight: 100
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Rg.otf
          weight: 400
        - asset: assets/fonts/LINE_Seed_Sans_KR_OTF/LINESeedKR-Bd.otf
          weight: 700